### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Gold-of-Danae** [hexojs/hexo-webui#29]
Hello,
Can someone please update the readme to explain how to add this to an existing hexo folder?
Thank you very much

**Comment by SukkaW** [comment]
Just run `npm i hexo-webui` under your current hexo folder.

However, it is not recommended to use this plugin since it hasn't been maintained for years.

**Comment by Gold-of-Danae** [comment]
@SukkaW okay thank you, will be installing hexo-admin instead!
